# Generated by Django 3.0 on 2019-12-17 03:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False)),
                ('project_text', models.CharField(blank=True, max_length=200)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('slug', models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False)),
                ('todo_text', models.CharField(blank=True, max_length=200)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
            ],
        ),
    ]
