# Generated by Django 3.0 on 2019-12-29 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('slug', models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False)),
                ('project_text', models.CharField(max_length=200, null=True)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('slug', models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False)),
                ('todo_text', models.CharField(max_length=200, null=True)),
                ('goal_date', models.DateTimeField(null=True)),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Project')),
            ],
        ),
        migrations.CreateModel(
            name='SubToDo',
            fields=[
                ('slug', models.AutoField(help_text='PK AutoIncrement', primary_key=True, serialize=False)),
                ('subtodo_text', models.CharField(max_length=200)),
                ('todo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.ToDo')),
            ],
        ),
    ]
