# Generated by Django 3.0 on 2019-12-19 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='goal_date',
            field=models.DateField(null=True),
        ),
    ]
