# Generated by Django 3.0 on 2019-12-19 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todo_goal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_text',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.Project'),
        ),
        migrations.AlterField(
            model_name='todo',
            name='todo_text',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
