# Generated by Django 3.0 on 2019-12-29 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20191229_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtodo',
            name='goal_date',
            field=models.DateTimeField(null=True),
        ),
    ]
