# Generated by Django 3.0 on 2020-03-19 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_subtodo_goal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtodo',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
